config/routes.rb
LunchRoulette::Application.routes.draw do
  resources :users
  resources :mailings

  root :to => 'users#new'
  match '/perform', to: 'mailings#new'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :num_lunches, :wants_lunch

  scope :all_wanting_lunch, where(wants_lunch: true)

  def self.domain
    ENV["USER_DOMAIN"]
  end

  def username
    email && email.split('@')[0]
  end

  def username=(first_dot_last)
    self.email = first_dot_last + '@' + User.domain
  end

  def first_name
    email.split('.')[0].capitalize
  end

  def add_lunch
    self.num_lunches = num_lunches + 1
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mailings_controller.rb
class MailingsController < ApplicationController
  http_basic_authenticate_with name: ENV["MAILING_NAME"], password: ENV["MAILING_PASSWORD"]

  def new
  end

  def create
    hour_of_day = Time.zone.now.hour  
    #if hour_of_day != 11
    #  redirect_to(new_mailing_path, notice: "Perform lunch roulette no earlier than 11am and no later than noon.") and return 
    #end unless !Rails.env.production?
    wanting_lunch = User.all_wanting_lunch.shuffle
    wanting_lunch.each_slice(4) do |lunch_group|
      if lunch_group.count > 1
        UserMailer.lunch_mailing(lunch_group).deliver
        lunch_group.each(&:add_lunch)
      else
        lunch_group.each { |user| UserMailer.sorry_mailing(user).deliver }
      end
    end
    wanting_lunch.each { |user| user.toggle!(:wants_lunch) } 
    flash[:success] = "Mailings sent."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with name: ENV["USER_NAME"], password: ENV["USER_PASSWORD"]

  def new
    @user = User.find_by_email(cookies[:lunch_roulette_email]) || User.new
  end

  def create
    @user = User.find_or_create_by_email(params[:user][:username] + '@' + User.domain)
    if @user.valid?
      cookies.permanent[:lunch_roulette_email] = @user.email
      @user.update_attribute(:wants_lunch, params[:user][:wants_lunch])
      if @user.wants_lunch
        flash[:success] = "Thanks, #{@user.first_name}! You'll get an email by noon with your lunch group." 
      else
        flash[:alert] = "That's unfortunate, #{@user.first_name}. Come back and check the box by 11am if you change your mind."
      end
      redirect_to root_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mailings_helper.rb
module MailingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Lunch Roulette
    = stylesheet_link_tag    "application", media: "all"
    = csrf_meta_tags
  %body
    .container
      - flash.each do |key, value|
        = content_tag :div, value, class: "alert alert-#{key}"
      = yield
      = javascript_include_tag "application"

app/views/mailings/new.html.haml
= form_tag mailings_path, method: :post do
  = submit_tag 'Lunch roulette!'

app/views/users/new.html.haml
= form_for(@user, url: users_path, method: :post) do  |f|
  .field
    = f.text_field :username
    = '@' + User.domain
  .field
    = f.label :wants_lunch, 'In?'
    = f.check_box :wants_lunch
  .field
    = f.submit 'Post'